enabled: true
matchtime: 130
peacetime: 10
FreezerItems:
  - STONE_AXE
  - STONE_PICKAXE
  - STONE_SHOVEL
WorldBorderSize: 100
RunnerItems:
  - OAK_WOOD_PLANKS
  - OAK_WOOD_PLANKS
  - OAK_WOOD_PLANKS
  - OAK_WOOD_PLANKS
  - OAK_WOOD_PLANKS
  - OAK_WOOD_PLANKS
  - OAK_WOOD_PLANKS
  - OAK_WOOD_PLANKS